version: '2.1'

networks:
  monitor-net:
    driver: bridge
volumes:

    grafana_data: {}

services:
  web:
    build: .
    ports:
      - "80:80"

  grafana:
    image: grafana/grafana:6.7.1
    container_name: grafana


    ports:
      - 3000:3000

